// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $cv from "./routes/cv.tsx";
import * as $index from "./routes/index.tsx";
import * as $posts from "./routes/posts.tsx";
import * as $stats from "./routes/stats.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LemonDrop from "./islands/LemonDrop.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/cv.tsx": $cv,
    "./routes/index.tsx": $index,
    "./routes/posts.tsx": $posts,
    "./routes/stats.tsx": $stats,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LemonDrop.tsx": $LemonDrop,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
